import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
const inter = Poppins({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="text-red-700">ERRRORs</h1>
        {/* <Provider>{children}</Provider> */}
        {children}
      </body>
    </html>
  );
}
